name: Bump Version and Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Check for manual version bump
        id: check-version
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $LAST_COMMIT_MSG == *"[skip-version-bump]"* ]]; then
            echo "Manual version change detected, skipping automatic bump"
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version automatically
        if: steps.check-version.outputs.skip == 'false'
        run: |
          # Default to patch bump, check commit message for minor/major
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if [[ $LAST_COMMIT_MSG == *"[minor]"* ]]; then
            npm version minor
          elif [[ $LAST_COMMIT_MSG == *"[major]"* ]]; then
            npm version major
          else
            npm version patch
          fi

      - name: Push version changes
        if: steps.check-version.outputs.skip == 'false'
        run: |
          git push
          git push --tags

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
